### PR TITLE
Fix test output directory redux

### LINKED ISSUE #119: test_run_aca_review_function failing from installed package
I'm getting:

sparkles/tests/test_review.py::test_run_aca_review_function FAILED

from my 32bit test environment when run with sparkles.test(verbose=1).  It also complains that it can't write out the error 

PermissionError: [Errno 13] Permission denied: '/export/aca/ska3matlab32/lib/python3.6/site-packages/.cache/v/cache/lastfailed'

back into my environment. 

The test passes if I run it directly in the sparkles repo directory

### PR DESCRIPTION
**Pull request by taldcroft**
Fixes #119 
Closes #120 (supercedes).

### CODE REVIEW

**Comment by jeanconn** [comment]
Sure.  This works.  I now see the output I expect in
```
pytest-of-jeanconn/pytest-30/test_run_aca_review_function0/
```
with no error run as the user who can't write back into the python libs.  It doesn't do cleanup but I don't think we care.

**Comment by taldcroft** [comment]
> It doesn't do cleanup but I don't think we care.

Normal testing protocol is to let `pytest` do the cleanup.

**Comment by jeanconn** [comment]
Is that just when it gets to certain NUM or some such?  I could go read the docs at some point.  I think we also want to update testr options at some point to keep pytest from doing other outputs in the tree (no:cacheprovider andPYTHONDONTWRITEBYTECODE=1 ?).

**Comment by taldcroft** [comment]
Perfect is the enemy of good!

**Comment by jeanconn** [comment]
I meant at some point, not for this release.   I still don't like any of our testing polluting our configured python environment, and these test actions can throw confusing errors when we don't have write permission back into that directory.

**Pull request merged**
