### PR TITLE
Update star mag, mag_err from AGASC

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

This allows updating the ACA catalog `mag` and `mag_err` columns when reading catalogs from a proseco pickle file.

The driving use case is prelim review of obsid 30580 in NOV1124. This special observation had a pathfinder which resulted in updates to the AGASC that were not yet reflected in the prelim catalogs.

## Interface impacts

None, this PR makes no changes by default.

### Unit tests

- [ ] Mac

Independent check of unit tests by [REVIEWER NAME]
- [ ] [PLATFORM]:

### Functional tests

Obsid 30580
#### With this PR
image

#### Master
image

### CODE REVIEW

**Comment by jeanconn** [comment]
I like this as a convenience, but maybe could use more convincing that it is necessary.  For similar cases we've used proseco to reselect with all stars force-include.

**Comment by taldcroft** [comment]
Yup, it is a convenience. For convincing:
- Reduces brainload and time since you don't have to open a notebook or IPython and write code.
- Works easily on an entire weekly schedule.
- I already wrote and tested the code and it does not substantially complicate the code and API.

**Comment by jeanconn** [comment]
Is this PR on hold for now or?

**Comment by taldcroft** [comment]
> Is this PR on hold for now or?

Nope. I am still hoping that you are convinced this is useful based on the points I mentioned.

**Comment by jeanconn** [comment]
Gotcha.  I thought for "Reduces brainload and time since you don't have to open a notebook or IPython and write code." that this PR made things worse as the one time we tried to use it, the subtleties of mag_err handling in proseco meant that we weren't on the same page with the FOT and the confusion was worse than brainload.

**Comment by jeanconn** [comment]
And I thought that you'd agreed that just using proseco to reselect was probably safer and simpler.  Alternatively we could probably remove that special mag_err handling in proseco.

**Comment by taldcroft** [comment]
Ok.

**Pull request closed without merging**
