### PR TITLE
Fix issue in naming of roll option plots

### PR DESCRIPTION
**Pull request by taldcroft**
The roll option plots had previously all wound up with the same name.  This was introduced in the PR that "improved" the roll handling.

### CODE REVIEW

**Comment by jeanconn** [comment]
I think this can be re-targeted as a PR against master.

**Comment by jeanconn** [comment]
So now I assume this is overcome by events by #76 and can be closed?

**Comment by taldcroft** [comment]
Not exactly overcome by events, but the commit of relevance here 4e3fcd8 is in #76.

**Comment by jeanconn** [comment]
Right.  I thought OBE was an OK description because that other commit was
merged in master.  Maybe should be Overcome By Commits.

**Comment by taldcroft** [comment]
OBE to me means the situation changed and the fix is no longer necessary.  My usual wording in this case is that a PR is superceded by another.

**Pull request closed without merging**
